# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: estimator.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x65stimator.proto\x12\testimator\"\x19\n\x0bMachineInfo\x12\n\n\x02id\x18\x01 \x01(\x05\"1\n\x11RemainingLifetime\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08lifetime\x18\x02 \x01(\x05\x32h\n\x11LifetimeEstimator\x12S\n\x19\x65stimateRemainingLifetime\x12\x16.estimator.MachineInfo\x1a\x1c.estimator.RemainingLifetime\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'estimator_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MACHINEINFO._serialized_start=30
  _MACHINEINFO._serialized_end=55
  _REMAININGLIFETIME._serialized_start=57
  _REMAININGLIFETIME._serialized_end=106
  _LIFETIMEESTIMATOR._serialized_start=108
  _LIFETIMEESTIMATOR._serialized_end=212
# @@protoc_insertion_point(module_scope)
