# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import maintenance_pb2 as maintenance__pb2


class MaintenanceRecommendationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMaintenanceRecommendations = channel.unary_unary(
                '/MaintenanceRecommendationService/GetMaintenanceRecommendations',
                request_serializer=maintenance__pb2.MachineState.SerializeToString,
                response_deserializer=maintenance__pb2.RecommendationList.FromString,
                )


class MaintenanceRecommendationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetMaintenanceRecommendations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MaintenanceRecommendationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMaintenanceRecommendations': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMaintenanceRecommendations,
                    request_deserializer=maintenance__pb2.MachineState.FromString,
                    response_serializer=maintenance__pb2.RecommendationList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MaintenanceRecommendationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MaintenanceRecommendationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetMaintenanceRecommendations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MaintenanceRecommendationService/GetMaintenanceRecommendations',
            maintenance__pb2.MachineState.SerializeToString,
            maintenance__pb2.RecommendationList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
