# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: maintenance.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11maintenance.proto\"m\n\x0cMachineState\x12\x1e\n\x06status\x18\x01 \x01(\x0e\x32\x0e.MachineStatus\x12\n\n\x02id\x18\x02 \x01(\x05\x12\x15\n\rruntime_hours\x18\x03 \x01(\x05\x12\x1a\n\x12remaining_lifetime\x18\x04 \x01(\x05\"G\n\x19MaintenanceRecommendation\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x1e\n\x04type\x18\x02 \x01(\x0e\x32\x10.MaintenanceType\"I\n\x12RecommendationList\x12\x33\n\x0frecommendations\x18\x01 \x03(\x0b\x32\x1a.MaintenanceRecommendation*7\n\rMachineStatus\x12\x08\n\x04IDLE\x10\x00\x12\x0b\n\x07RUNNING\x10\x01\x12\x0f\n\x0b\x42ROKEN_DOWN\x10\x02*K\n\x0fMaintenanceType\x12\x0e\n\nPREVENTIVE\x10\x00\x12\x0e\n\nCORRECTIVE\x10\x01\x12\x0e\n\nPREDICTIVE\x10\x02\x12\x08\n\x04NONE\x10\x03\x32i\n MaintenanceRecommendationService\x12\x45\n\x1dGetMaintenanceRecommendations\x12\r.MachineState\x1a\x13.RecommendationList\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'maintenance_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MACHINESTATUS._serialized_start=280
  _MACHINESTATUS._serialized_end=335
  _MAINTENANCETYPE._serialized_start=337
  _MAINTENANCETYPE._serialized_end=412
  _MACHINESTATE._serialized_start=21
  _MACHINESTATE._serialized_end=130
  _MAINTENANCERECOMMENDATION._serialized_start=132
  _MAINTENANCERECOMMENDATION._serialized_end=203
  _RECOMMENDATIONLIST._serialized_start=205
  _RECOMMENDATIONLIST._serialized_end=278
  _MAINTENANCERECOMMENDATIONSERVICE._serialized_start=414
  _MAINTENANCERECOMMENDATIONSERVICE._serialized_end=519
# @@protoc_insertion_point(module_scope)
